#!/usr/bin/env python3
import socket
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("port")

    args = parser.parse_args()
    port = int(args.port)

    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    s.bind(('', port))
    s.listen(5)

    file = open('worm',mode='r')
    all_of_it = file.read()
    while True:
        conn, addr = s.accept()
        conn.send(all_of_it.encode())
        conn.close()